# --- FUENTES ---
# font_family      MesloLGS NF
font_family	 JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- MAPEO DE ÍCONOS (NERD FONTS) ---
# Esto para que Kitty dibuje todos estos rangos Unicode (donde viven los íconos) 
# usando la fuente "Symbols Nerd Font" en lugar de JetBrains Mono.
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font


# --- APARIENCIA ---
background_opacity 0.95
# En Ubuntu (Wayland), ocultar las decoraciones a veces quita la capacidad de arrastrar 
# la ventana con el mouse fácilmente. Ponlo en 'yes' si prefieres usar la tecla Super (Windows) + click para arrastrar.
hide_window_decorations no 
# Atenuar texto sin foco
inactive_text_alpha 0.8

# layuout por default el primero
enabled_layouts splits, *

# --- BORDES ---
window_border_width 1pt
active_border_color #00ff00
inactive_border_color #444444
# window_margin_width 1
# Margen entre el borde y el texto
window_padding_width 4

# --- TAMAÑO INICIAL ---
remember_window_size  no
initial_window_width  80c
initial_window_height 25c

# BEGIN_KITTY_THEME
# Dainty Dark
include current-theme.conf
# END_KITTY_THEME


# --- SPLITS ---
# Vertical con Enter
map ctrl+enter launch --location=vsplit --cwd=current

# Horizontal con Backspace
map ctrl+backspace launch --location=hsplit --cwd=current

# Navegación con llaves
map kitty_mod+{ previous_window
map kitty_mod+} next_window

# Mover panel actual a una nueva tab
map kitty_mod+m detach_window new-tab


# --- RESIZE DIRECTO ---
map ctrl+super+left resize_window narrower
map ctrl+super+right resize_window wider
map ctrl+super+up resize_window taller
map ctrl+super+down resize_window shorter

# --- YAZI ---
# Abrir Yazi en un panel vertical (como explorador lateral)
map ctrl+e launch --type=window --location=vsplit --cwd=current zsh -ic "yy; exec zsh"

# --- RE-MAP ---
map ctrl+f2 edit_config_file

# Switch to specific layout
map ctrl+alt+s goto_layout splits

map kitty_mod+t new_tab_with_cwd


# --- IMAGEN DE FONDO ---
# Ruta absoluta a la img
#background_image /home/eze/Pictures/fondo-term/boca-mono-libertadores.jpeg
#background_image /home/eze/Pictures/fondo-term/nubes.png
background_image /home/eze/Pictures/fondo-term/space-pixel.png
#background_image /home/eze/Pictures/fondo-term/forest-pixel.png

# ¿Cómo se ajusta la imagen? 
# Opciones: centered, scaled (estira y deforma), cscaled (estilo 'cover', no deforma), tiled (repite)
background_image_layout cscaled

# Interpolación lineal. 'yes' para que se vea suave, o 'no' si es pixel-art
background_image_linear no

# TINT (El salvavidas visual)
# Mezcla la imagen con el color de fondo de tu terminal (usualmente negro).
# 0.0 es la imagen original (tus ojos van a sangrar intentando leer código).
# 1.0 es el color sólido (la imagen desaparece).
# Un valor entre 0.8 y 0.95 suele ser el punto dulce para que sea un detalle estético sutil.
background_tint 0.95
